config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'polls#index'
  resources :polls do
    resources :answers do
      member do
        patch "upvote", to: "answers#upvote"
      end
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :poll

  validates :title, presence: true
  
  acts_as_votable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :polls, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_voter

  def username
    email.split('@')[0].capitalize
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController  

  def upvote
    @poll = Poll.find(params[:id])
    @answer = @poll.answers.find(params[:poll_id])

    if user_signed_in?
      flash.notice = "Thank you for voting."
      @answer.upvote_by current_user
    end

    render "vote.js.erb"
  end
  
  def create
    @poll = Poll.find(params[:poll_id])
    @answer = @poll.answers.create(answer_params)
    render "_form.html.erb"
  end

  def destroy
    @poll = Poll.find(params[:poll_id])
    @answer = @poll.answers.find(params[:id])
    @answer.destroy
    redirect_to poll_path(@poll)
  end
  
  private

  def answer_params
    params.require(:answer).permit(:title)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :is_admin!

  def is_admin!
    if user_signed_in?
      unless current_user&.admin
        redirect_to root_path
      end
    end
  end
  
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  skip_before_action :authenticate_user!, only: %i[show]
  before_action :is_admin!, only: %i[new, create, edit, update, destroy]

  def index
    @polls = Poll.all
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def new
    @poll = Poll.new
  end
  
  def create
    @poll = current_user.polls.build(poll_params)

    if @poll.save
      redirect_to @poll
    else
      render :new
    end
  end

  def edit
    @poll = Poll.find(params[:id])
  end
  
  def update
    @poll = Poll.find(params[:id])

    if @poll.update(poll_params)
      redirect_to @poll
    else
      render :edit
    end
  end
  
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    redirect_to root_path
  end
  
  private

  def poll_params
    params.require(:poll).permit(:title)
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<div class="admin-show-wrapper">

  <% if user_signed_in? %>
    <% if !current_user.admin %>
      <%= link_to upvote_poll_answer_path(answer), method: :patch, remote: true, id: "upvote-#{answer.id}", class: "vote-btn" do %>    
        <p class="answer-box">

          <% if user_signed_in? %>
            <%= answer.title %>
          <% else %>
            <%= "Sign in to vote!" %>
          <% end %>

        </p>
      <% end %>
    <% end %>
  <% else %>
    <p class="answer-box">

      <% if !user_signed_in? %>
        <%= answer.title %>
      <% else %>
        <%= "Sign in to vote!" %>
      <% end %>

    </p>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.admin %>
      <p class="delete-answer">
        <%= link_to 'Destroy Answer', [answer.poll, answer], method: :delete, data: { confirm: "Are you sure?"} %>
      </p>
      <p class="answer-box">
        <%= answer.title %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/answers/_form.html.erb
<%= form_with model: [ @poll, @poll.answers.build ] do |f| %>
  <p class="input-new-answer">
    <%= f.text_field :title %>
  </p>
  <p class="create-new-answer">
    <%= f.submit %>
  </p>
  <li class="go-to-new-poll"><%= link_to "Go to created Poll", poll_path(@poll) %></li>
<% end %>

app/views/answers/vote.js.erb
document.getElementById("upvote-<%= @answer.id %>").innerHTML = "<%= j render "answers/answer", answer: @answer %>";
window.location.reload()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PollApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a1c63c884d.js" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kurenaido&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>

    <% flash.each do |type, msg| %>
      <div class="notice alert">
        <%= msg %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render partial: 'shared/signature' %>
  </body>
</html>

app/views/poll/index.html.erb
<h1>Polls</h1>

<ul>
  <% @polls.each do |poll| %>
    <li>
      <%= link_to poll.title, poll %>
    </li>
  <% end %>
</ul>

app/views/polls/_form.html.erb
<%= form_with model: poll do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% poll.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/_thanks.html.erb
<div class="thank-you-notice">
  <%= "Your vote was registered successfully!" %>
  <br>
  <%= "Thank you for participating!" %>
  <br> <br>
  <%= "Keep and eye on your inbox, the results will be shared soon." %>
</div>

app/views/polls/edit.html.erb
<h1>Edit Poll</h1>

<%= render "form", poll: @poll %>

app/views/polls/index.html.erb
<div class="index-container">
  <% if user_signed_in? %>
    <%# signed in as admin %>
    <% if current_user.admin %>
      <h1>Polls lined up</h1>
      <ul class="current-polls">
        <% if @polls.length == 0 %>
          <span class="current-focus-poll">
            Hi <%= current_user.username %> 👋
          </span>
          <br>
          <span class="current-focus-poll">
            No polls are lined up right now.
          </span>
          <br> <br>
          <span class="current-focus-poll">
            Create a new poll.
          </span>
          <br> <br>
          <span class="arrow-to-newPoll">
            <i class="fas fa-chevron-down"></i>
          </span>
          <span class="arrow-to-newPoll">
            <i class="fas fa-chevron-down"></i>
          </span>
        <% end %>

        <% @polls.each do |poll| %>
          <li class="lined-up-poll">
            <%= link_to poll.title, poll %>
          </li>
        <% end %>
      </ul>
    <% else %>
    <%# signed in as normal user %>
      <h1>Focus Poll</h1>
      <% current_poll = @polls.first %>
      <% if @polls.length > 0 %>
        <%= link_to current_poll.title, current_poll, class: "current-focus-poll-loggedIn" %>
      <% else %>
        <span class="current-focus-poll">
          Hi <%= current_user.username %> 👋
        </span>
        <br>
        <span class="current-focus-poll">
          No polls are life right now.
        </span>
        <span class="current-focus-poll">
          Please check again later.
        </span>
      <% end %>
    <% end %>

  <% else %>
    <%# if not signed in %>
    <h1>Focus Poll</h1>
    <% current_poll = @polls.first %>
    <% if @polls.length > 0 %>
      <span class="current-focus-poll">
        <%= link_to current_poll.title, current_poll %>
      </span>
    <% else %>
      <span class="current-focus-poll">
        No polls are life right now.
      </span>
      <span class="current-focus-poll">
        Please check again later.
      </span>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.admin %>
      <%= link_to "New Poll", new_poll_path, class: "new-poll" %>
    <% end %>
  <% end %>
</div>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= form_with model: @poll do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% @poll.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/show.html.erb
<div class="show-container">
  
  <div class="poll-title">
    <h1><%= @poll.title %></h1>
  </div>
  <% if !user_signed_in? %>
    <div class="participate">
      <span class="participate-msg">
        Sign in to <ruby class="participate-inner-msg">participate<rt>↗</rt></ruby>
      </span>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.admin %>
      <ul class="poll-settings">
        <li class="edit-poll"><%= link_to "Edit Poll", edit_poll_path(@poll) %></li>
        <li class="delete-poll"><%= link_to "Delete Poll", poll_path(@poll), method: :delete, data: { confirm: "Are you sure?"} %></li>
      </ul>
    <% end %>
  <% end %>

  <h3 class="select-answer">Select your answer:</h3>

  <% answers_amount = @poll.answers.size %>
  <% if answers_amount == 0%>
    <h5>Add a possible answer to your question:</h5>
    <%= render 'answers/form' %>
  <% end %>

  <% if answers_amount > 0 %>
    <% if user_signed_in? %>
      <% user_votes = current_user.votes.up.votables.size %>
      <% if user_votes > 0 %>
        <%= render 'polls/thanks' %>
      <% else %>
        <%= render @poll.answers %>
      <% end %>
    <% else %>
      <%= render @poll.answers %>
    <% end %>
  
    <% if user_signed_in? %>
      <% if current_user.admin %>

        <div class="results-wrapper">

          <div class="table-wrapper">
            <table class="results-table">
              <thead class="table-mainhead">
                <tr class="table-row">
                  <th class="table-header">Votes</th>
                  <th class="table-header">Answers</th>
                </tr>
              </thead>

              <tbody class="table-body">
                <% @poll.answers.each do |answer| %>
                  <% if answer.votes_for.size > 0 %>
                    <tr class="table-row">
                      <td class="answer-votes"><%= answer.votes_for.size %></td>
                      <td class="answer-title"><%= answer.title %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="pie-graph-wrapper">
            <canvas id="myChart_2" aria-label="Focus Polls Results" role="img"></canvas>
          </div>

        </div>
        <div class="bar-graph-wrapper">
          <canvas id="myChart" aria-label="Focus Polls Results" role="img"></canvas>
        </div>

      <% end %>
    <% end %>

  <% end %>

</div>
<br>
<%= link_to "Home", root_path, class: "homelink" %>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="navbar">
    <div class="navbar-logo">
      <%= link_to root_path, class: "logo" do %>
        <i class="far fa-comments fa-2x"></i>
      <% end %>
    </div>

    <div class="menu-navigation">
      <% if user_signed_in? %>
        <% if current_user.admin %>
          <%= link_to "New Poll", new_poll_path, class: "nav-new-poll" %>
        <% end %>
      <% end %>
    </div>

    <div class="menu-navigation">
      <% if user_signed_in? %>
        <span>Logged in as: <strong><%= current_user.username %></strong></span>
        <%= link_to edit_user_registration_path, class: "nav-settings" do %>
          <i class="fas fa-cog fa-2x"></i>
        <% end %>

        <%= link_to destroy_user_session_path, method: :delete, class: "logOut" do %>
          <i class="fas fa-sign-out-alt fa-2x"></i>
        <% end %>
      <% end %>

      <% if !user_signed_in? %>
        <%= link_to new_user_session_path, class: "logIn" do %>
          <i class="far fa-user-circle fa-2x"></i>
        <% end %>
      <% end %>

    </div>

  </div>
</div>

app/views/shared/_signature.html.erb
<div class="signature">
  <p>Created by <ruby>Diego Boy<rt>👋"Hi there!"</rt></ruby></p>
</div>